name: Build and Deploy to gh-pages

on:
  push:
    branches:
      - main  # Replace with your main branch name

variables: 
  OUTPUT_DIR: docs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: $OUTPUT_DIR  # Specify your build output directory
