name: Build and Deploy to gh-pages

on:
  push:
    branches:
      - master
      - development

env:
  OUTPUT_DIR: dist

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure GitHub npm registry
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PAT }}" > ~/.npmrc
          echo "@OWNER:registry=https://npm.pkg.github.com" >> ~/.npmrc
        env:
          OWNER: danielgroen

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.OUTPUT_DIR }}
